config/routes.rb
OtVideoParty::Application.routes.draw do

  root :to => "rooms#index"

  resources :rooms

  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
  match 'rooms/upload'
  post 'rooms/get_files_from_room' => 'rooms#get_files_from_room', :as => 'get_room_files'

end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name, :public, :sessionId
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def upload
    uploaded_io = params[:file]
    name = params[:file].original_filename
    directory = "public/uploads/"+params[:room]
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(uploaded_io.read) }
    #File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
    #  file.write(uploaded_io.read)
    #end

    #send_file path, :type => 'image/png', :disposition => 'inline'#, :filename => params[:file].original_filename
    #,:type => "application/pdf"
    respond_to do |format|
      format.json {render :json => ''}
    end
  end



  def index
    @rooms = Room.where(:public => true).order("created_at DESC")
    @new_room = Room.new
  end

  def get_files_from_room
    #Dir.glob("/path/to/my/directory/**/*")
    #{"dirs":"'+Dir.glob("/uploads/"+params[:room]+"/**/*")+'"}
    dirs = Dir.entries("#{Rails.root.to_s}/public/uploads/"+params[:room].to_s)#Dir.glob("#{Rails.root.to_s}/public/uploads/22/**/*").to_s
    json_text = { :room => params[:room].to_s, :dirs => dirs }.to_json
    respond_to do |format|
      format.json {render :json => JSON.parse(json_text)}
      format.html
    end
  end

  def create
    config_opentok
    session = @opentok.create_session request.remote_addr
    params[:room][:sessionId] = session.session_id
    @new_room = Room.new(params[:room])
    respond_to do |format|
      if @new_room.save
        Dir.mkdir "#{Rails.root.to_s}/public/uploads/" +@new_room.id.to_s
        format.html { redirect_to("/party/"+@new_room.id.to_s) }
      else
        format.html { render :controller => 'rooms',
               :action => "index" }
      end
    end
  end

  def party
    @room = Room.find(params[:id])

    config_opentok

    @tok_token = @opentok.generate_token :session_id =>
          @room.sessionId
  end

  private
  def config_opentok
    if @opentok.nil?
      @opentok = OpenTok::OpenTokSDK.new 28878252, "ae478e8c6003c84324dd48305d6232b703454e62"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
require 'date'

module RoomsHelper

  def start_diff(date)
    intervals = [["day", 1], ["hour", 24], ["minute", 60], ["second", 60]]
    elapsed = DateTime.now - DateTime.parse(date.to_s)
    #tense = elapsed > 0 ? "since" : "until"
    #event = elapsed > 0 ? "the Video Party started" : "the Video Party starts"
    interval = 1.0
    parts = intervals.collect do |name, new_interval|
      interval /= new_interval
      number, elapsed = elapsed.abs.divmod(interval)
    "#{number.to_i} #{name}#{"s" unless number == 1}"
    end
    "#{parts.join(", ")} ago."
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoParty</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1>Gurube</h1>
     <!-- <h1>Video Party</h1>
      <h3>[Start or join a video party, invite your friends but most of all have fun!]</h3>
    -->
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <!--<p>&copy; 2011, <a href="http://therainbowhatguy.com" title="The Rainbow Hat Guy Talks">Melih Onvural</a> - Distributed under MIT License on <a href="https://github.com/monvural/OpenTok-Video-Party">GitHub</a></p>
      <p>If you have any questions, or would like to see some improvements, please e-mail <a href="mailto:melih.onvural@gmail.com">melih.onvural {at} gmail {dot} com</a></p>
    -->
    </div>
  </div>
</body>
</html>

app/views/rooms/_newform.html.erb
<fieldset>
	<legend>Start a new party room</legend>

        <%= form_for(@new_room) do |f| %>
  	Party Name: <%= f.text_field :name %><br/><br/>
  	Public? <%= f.check_box :public %><br/><br/>

	<%= f.submit %>
<% end %>
</fieldset>

app/views/rooms/index.html.erb
<div id="newRoom">
  <%= render 'rooms/newform' %>
</div>

<fieldset>
  <legend>Existing party rooms</legend>
<table cellpadding="2" cellspacing="5">
  <tr>
    <th>Name</th>
    <th>Started</th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td align="center" width="300px"><a href="/party/<%= room.id %>"><%= room.name %></a></td>
    <td><%= start_diff(room.created_at) %></td>
  </tr>
<% end %>
</table>
</fieldset>

app/views/rooms/new.html.erb
<h1>New test</h1>

<%= render 'newform' %>

<%= link_to 'Back', tests_path %>

app/views/rooms/party.html.erb
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" />
<%= javascript_include_tag "jquery.countdown.js" %>
<%= stylesheet_link_tag "jquery.countdown.css" -%>

        <div id="countdown"></div>

        <div class="row-fluid">
        <div class="span4" id="dropfile">
          Drag Files here
        </div>
        <div class="span4">
          <!--<form action="" class="dropzone" id="my_dropzone"></form>-->
          <%#= form_tag({:controller => 'rooms', :action => 'upload'},:method => 'get', :multipart => true,  :class => "dropzone", :id => "my_dropzone") do %>
          <% #end %>
        </div>
        <div class="span4">
        </div>
      </div>

<br />

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span9">

      <center>
        Aquí van los invitados c:

        
        <div id="videobox" >

        </div>
      </center>

    </div>

    <div class="span3" id="myself">
      <input type="button" id="audioStatusButton" onclick="changeAudioStatus()" value="enabledAudio"></input>
        <input type="button" id="videoStatusButton" onclick="changeVideoStatus()" value="enabledVideo"></input>
      <center>

      <div id="myselfbox" >

        </div>
      </center>
  </div>
</div>

<script src='https://swww.tokbox.com/webrtc/v2.0/js/TB.min.js'></script>
<script type="text/javascript">
	var apiKey = 28878252;
	var sessionId = "<%= @room.sessionId %>";
	var token = "<%= @tok_token %>";

	var session;
      var publisher;

	TB.addEventListener('exception', exceptionHandler);
	session = TB.initSession(sessionId);

	//Video chat event listeners
	session.addEventListener('sessionConnected', sessionConnectedHandler);
	session.addEventListener('streamCreated', streamCreatedHandler);
    session.addEventListener('streamDestroyed', streamDestroyedHandler);

	session.connect(apiKey, token);


//Files







function get_files(){
    $("#dropfile").html("<h2>Archivos Compartidos</h2>Arrastra o haz click aqui para agregar")
    $("#dropfile").width(300)
    $("#dropfile").height(300)

  $.ajax({
    type: "POST",
    url: '<%=get_room_files_path %>',
    data: {"room":"<%= @room.id%>"},
    dataType: 'JSON'
  }).done(function(data) {
    console.log("asdf!!"+JSON.stringify(data))
    for (dir in data.dirs)
    {
      if (data.dirs[dir] != "." && data.dirs[dir] != "..")
      {
        console.log(data.dirs[dir])
        $("#dropfile").append('<br /><a link="/uploads/<%= @room.id.to_s%>/'+data.dirs[dir]+'" class="downloadLink">Descargar '+data.dirs[dir]+'</a>')

      }
    }
        $(".downloadLink").on("click",function(){
          console.log("lala")
          window.open($(this).attr("link"),'_blank');
        })
  }).fail(function(jqXHR, textStatus, errorThrown) {
    console.log( "Request failed: " + jqXHR.fail().toString() );
  });
}


var myDropzone = new Dropzone("div#dropfile", { url: "/rooms/upload",parallelUploads: 1})

$(document).ready(function(){

get_files()




  //myDropzone = Dropzone.forElement("#dropfile");
  myDropzone.on("sending", function(file, xhr, formData) {
    formData.append("room", '<%=@room.id.to_s%>');
  });
  myDropzone.on("dragenter", function(event) {
    console.log("Entering that on that")
    $("#dropfile").html("Dropme here!! here!!!")
  });
  myDropzone.on("dragover", function(event) {
    console.log($("#dropfile").height()+"Dragging that over here"+$("#dropfile").width())
    var w = $("#dropfile").width()
    var h = $("#dropfile").height()
    $("#dropfile").html("Dropme here!! here!!!")
    $("#dropfile").width(720)
    $("#dropfile").height(300)
  });
  myDropzone.on("dragleave", function(event) {
    console.log("Dont stop dragging!! :(")
   // get_files()
  });

  myDropzone.on("complete",function(file){
    console.log(file)
    //$("#dropfile").append('<a href="/uploads/<%= @room.id.to_s%>/'+file.name+'">Download '+file.name+'</a>')
    //file.previewElement.click(function() { alert("clicked"+file.name)});
    //$(".dz-preview").last().on("click",function(){ window.open("/uploads/<%= @room.id.to_s%>/"+file.name);console.log('did it work?')})
    get_files()
  })
})

window.setInterval(function(){
  get_files()
}, 5000);

  function changeVideoStatus() {

    var button = document.getElementById("videoStatusButton");

    if (button.value == "enabledVideo") {
      button.value = "disabledVideo";
      publisher.publishVideo(false);
    }

    else {
      button.value = "enabledVideo";
      publisher.publishVideo(true);
    }
  }

  function changeAudioStatus() {

    var button = document.getElementById("audioStatusButton");

    if (button.value == "enabledAudio") {
      button.value = "disabledAudio";
      publisher.publishAudio(false);
    }

    else {
      button.value = "enabledAudio";
      publisher.publishAudio(true);
    }
  }



// Countdown
$(function(){

  var note = $('#note'),
    ts = new Date(2012, 0, 1),
    newYear = true;

  if((new Date()) > ts){
    // The new year is here! Count towards something else.
    // Notice the *1000 at the end - time must be in milliseconds
    ts = (new Date()).getTime() + 1*1*29*60*1000;
    newYear = false;
  }

  $('#countdown').countdown({
    timestamp : ts,
    callback  : function(days, hours, minutes, seconds){

      var message = "";

      message += days + " day" + ( days==1 ? '':'s' ) + ", ";
      message += hours + " hour" + ( hours==1 ? '':'s' ) + ", ";
      message += minutes + " minute" + ( minutes==1 ? '':'s' ) + " and ";
      message += seconds + " second" + ( seconds==1 ? '':'s' ) + " <br />";

      if(newYear){
        message += "left until the new year!";
      }
      else {
        message += "left to 10 days from now!";
      }

      note.html(message);
    }
  });

});



</script>

 <!--
<script src='https://swww.tokbox.com/webrtc/v2.0/js/TB.min.js'></script>
<div id="myPublisherDiv"></div>
        <script type="text/javascript">
          // Initialize API key, session, and token...
          // Think of a session as a room, and a token as the key to get in to the room
          // Sessions and tokens are generated on your server and passed down to the client
          var apiKey = "28873032";
          var sessionId = "<%= @room.sessionId %>";
          var token = "<%= @tok_token %>";

          // Initialize session, set up event listeners, and connect
          var session = TB.initSession(sessionId);
          session.addEventListener('sessionConnected', sessionConnectedHandler);
          session.connect(apiKey, token);

          function sessionConnectedHandler(event) {
            var publisher = TB.initPublisher(apiKey, 'myPublisherDiv');
            session.publish(publisher);
          }
        </script>
-->